// WordPress webpack config.
const [
	scriptsConfig,
	moduleConfig,
] = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = [
	scriptsConfig,
	moduleConfig,
	{
		...scriptsConfig,
		...{
			entry: {
				'scg-theme': path.resolve(
					process.cwd(),
					'src/styles',
					'scg-theme.scss'
				),
				'scg-content': path.resolve(
					process.cwd(),
					'src/styles',
					'scg-content.scss'
				),
				'scg-scripts': path.resolve(
					process.cwd(),
					'src/scripts',
					'scg.js'
				),
				'scg-editor-scripts': path.resolve(
					process.cwd(),
					'src/scripts',
					'scg-editor.js'
				),
			},
			plugins: [
				// Include WP's plugin config.
				...scriptsConfig.plugins,

				// Removes the empty `.js` files generated by webpack but
				// sets it after WP has generated its `*.asset.php` file.
				new RemoveEmptyScriptsPlugin( {
					stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
				} ),
			],
			stats: {
				warnings: false,
			},
		},
	},
];
